### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by daangeijs** [sjoerdk/dicomtrolley#10]
Now:
trolley = Trolley(searcher=Mint(session, "https://server/mint"),
                  **wado**=Wado(session, "https://server/wado"]))

Should be changed to:
trolley = Trolley(searcher=Mint(session, "https://server/mint"),
                  **downloader**=Wado(session, "https://server/wado"]))

**Comment by sjoerdk** [comment]
Thanks for the heads-up!  Fixed in a08ae3455bf7f5eabc
