### ISSUE TITLE
WADO connection required to only query PACS

### ISSUE THREAD

**Issue by michelkok** [sjoerdk/dicomtrolley#2]
We usually first find studies in the PACS and then later decide to either download the corresponding DICOMs (or reports). Only for downloading the images you need wado. However, upon initialization of the trolley, this is already required.

I would expect this to be optional, and only when `trolley.download` is called, that we need to give a wado-connection as well.

**Comment by sjoerdk** [comment]
The [examples/search_for_studies_dicom_qr.py](https://github.com/sjoerdk/dicomtrolley/blob/master/examples/search_for_studies_dicom_qr.py) shows how to do a search without initializing WADO.  You use the Searcher instance separately and do not instantiate a Trolley
